# Generated by Django 4.0.6 on 2022-08-29 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edetcap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postgrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('level', models.CharField(choices=[(600, 600), (700, 700)], max_length=50)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edetcap.session')),
            ],
            options={
                'verbose_name': 'Postgrad',
                'verbose_name_plural': 'Postgrads',
                'ordering': ['-created_at'],
            },
        ),
    ]
