# Generated by Django 4.0.6 on 2022-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edetcap', '0002_postgrad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-academic_session'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='postgrad',
            name='level',
            field=models.CharField(choices=[(600, 600), (700, 700), (800, 800)], max_length=10),
        ),
    ]
