# Generated by Django 4.0.6 on 2022-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edetcap', '0003_alter_session_options_alter_postgrad_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgrad',
            name='department',
            field=models.CharField(choices=[('Mass Comm', 'Mass Comm'), ('Law', 'Law'), ('Bio-Chem', 'Bio-Chem'), ('Civil-Eng', 'Civil-Eng'), ('Nursing', 'Nursing')], default='Nursing', max_length=20),
        ),
    ]
