# Generated by Django 4.0.6 on 2022-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edetcap', '0005_alter_postgrad_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystaff',
            name='passport',
            field=models.ImageField(default='programmer.png', upload_to='staff/passport'),
        ),
    ]
