# Generated by Django 4.0.6 on 2022-09-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edetcap', '0007_undergrad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgrad',
            name='staff_id',
            field=models.CharField(help_text='Matric Id if student', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(help_text='Matric Id if student', max_length=50),
        ),
        migrations.CreateModel(
            name='VentureStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('designation', models.CharField(help_text='As written in appointment letter', max_length=50)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3)),
                ('passport', models.ImageField(default='programmer.png', upload_to='staff/passport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edetcap.session')),
            ],
            options={
                'verbose_name': 'VentureStaff',
                'verbose_name_plural': 'Ventures',
                'ordering': ['-created_at'],
            },
        ),
    ]
